version: "3"
services:

  backend:
    image: bitnami/laravel:9
    container_name: "backend"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: smartlyfe
      MYSQL_USER: smartlyfe
      MYSQL_PASSWORD: smartlyfe
      MYSQL_DATABASE: smartlyfe
    volumes:
      - smartlyfe-db:/var/lib/mysql

volumes:
  smartlyfe-db: