version: '3.1'
services:
  db:
    image: arm64v8/mysql:oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Downloads/phpmyadmin.sql:/phpmyadmin.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
     - PMA_ARBITRARY=1
     - MYSQL_ROOT_PASSWORD=root

